<?php $this->headTitle('Admin') ?>
<div class="page-header">
    <h1>Admin</h1>
</div>
<div class="row">
<?php
$flash = $this->flashMessenger();
echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Título</th>
            <th>Contenido</th>
        </tr>  
        </thead>
        <tbody>          
    <?php foreach ($entradas as $entrada): ?>
        <tr>
            <td><?php echo $entrada->getTitulo() ?></td>
            <td><?php echo $entrada->getContenido() ?></td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="row">
    <a class="btn btn-default" href="<?php echo $this->url('admin/nuevo')  ?>">Crear nueva entrada</a>
</div>
