<div class="col-md-8 col-md-offset-2">
<?php foreach ($paginador as $entrada): ?>
<div class="row">
    <h2>
        <a href="<?php echo $this->url('entrada', array('id' => $entrada->getId())); ?>">
            <?php echo $entrada->getTitulo(); ?>
        </a>
    </h2>
    <p><?php echo $entrada->getResumen() ?></p>
    <p class="text-right">
        <a href="<?php echo $this->url('entrada', array('id' => $entrada->getId())); ?>">
            Leer post &raquo;
        </a>
    </p>
    <hr />
</div>
<?php endforeach; ?>
<div class="row">
    <div class="text-center">
    <?php echo $this->paginationControl($paginador, 'Sliding', 'application/paginador', array('route' => 'archivo')); ?>
    </div>
</div>
</div>
<div class="clearfix"></div>
