<div class="jumbotron">
    <h1><?php echo $this->translate('Curso de ZF2 - Blog') ?></h1>
    <p><?php echo sprintf($this->translate('En este ejemplo vamos a hacer un blog con un ABM bien simple. Usaremos la versión %s de ZF2.'), \Zend\Version\Version::VERSION) ?></p>
</div>

<div class="row">

    <?php foreach ($entradas as $entrada): ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $entrada->getTitulo() ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $entrada->getResumen() ?></p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('entrada', array('id' => $entrada->getId())); ?>"><?php echo $this->translate('Leer post') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <?php endforeach; ?>

</div>
